name: Release

on:
  push:
    tags:
      - boost-*

jobs:
  release-posix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Create archives
        run: |
          rm -rf ${{ github.ref_name }}/.git
          tar -czf ${{ github.ref_name }}.tar.gz ${{ github.ref_name }}
          tar -cJf ${{ github.ref_name }}.tar.xz ${{ github.ref_name }}

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.ref_name }}.tar.gz
            ${{ github.ref_name }}.tar.xz

  release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Create archives
        run: |
          rd /r/q ${{ github.ref_name }}/.git
          7z ${{ github.ref_name }}.zip -r ${{ github.ref_name }}
          7z ${{ github.ref_name }}.7z -r ${{ github.ref_name }}

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.ref_name }}.zip
            ${{ github.ref_name }}.7z
