name: Release

on:
  push:
    tags:
      - '**'

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }} -r

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
